Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using SpotifyAPI.Web;

namespace MatchMusic.Models
{
    public class User
    {
        [Key]
        [Column(TypeName = "varchar(30)")]
        public string UserId { get; set; }
        
        [Required]
        [Column(TypeName = "nvarchar(60)")]
        public string UserName { get; set; }

        [Column(TypeName = "varchar(30)")]
        public string UserCode { get; set; }
        public ICollection<UserMatch> MatchedUsers { get; set; } = new List<UserMatch>();

        public ICollection<UserArtist> UsersArtists { get; set; } = new List<UserArtist>();

        public ICollection<UserTrack> UsersTracks { get; set; } = new List<UserTrack>();

        [Column(TypeName = "varchar(100)")]
        public string UserProfilePicture { get; set; }
        
      
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MatchMusic.Models;
using Microsoft.AspNetCore.Authentication;

namespace MatchMusic.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            
            return View();
        }

        [HttpGet]
        public async Task Login()
        {
            await HttpContext.ChallengeAsync("Spotify", new AuthenticationProperties() { RedirectUri = "https://localhost:44355/Users/Build" });
        }

        [HttpPost]
        public IActionResult Try(string userCode)
        {
            return View("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MatchesController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MatchMusic.Models;
using Microsoft.AspNetCore.SignalR;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SpotifyAPI.Web;

namespace MatchMusic.Controllers
{
    public class MatchesController : Controller
    {
        private readonly MatchMusicContext _context;
        private readonly SpotifyClientBuilder _spotifyClientBuilder;
        private User _currentUser;
        private User _secondUser;
        private Match _match;
        public MatchesController(MatchMusicContext context, SpotifyClientBuilder spotifyClient)
        {
            _context = context;
            _spotifyClientBuilder = spotifyClient;
            _currentUser = new User();
            _secondUser = new User();
            _match = new Match();
        }

        public async Task SetCurrentUser()
        {
            var spotifyClient = await _spotifyClientBuilder.CreateClient();

            var user = await spotifyClient.UserProfile.Current();
            _currentUser.UserId = user.Id;
        }
       

        public async Task<IActionResult> Match(string userCode)
        {
            await SetCurrentUser();

            var secondUser = await _context.Users
                .FirstOrDefaultAsync(m => m.UserCode == userCode);
            if (secondUser == null)
            {
                return RedirectToAction("NotFound", "Users", new {id = _currentUser.UserId});
            }
            _secondUser.UserId = secondUser.UserId;

            var currentUser = await _context.Users
                .FirstOrDefaultAsync(m => m.UserId == _currentUser.UserId);
            
            if (currentUser == null)
            {
                return RedirectToAction("NotFound", "Users", new { id = _currentUser.UserId });
            }

            if (secondUser.UserId == currentUser.UserId)
            {
                return RedirectToAction("NotFound", "Users", new { id = _currentUser.UserId });
            }
           
            ViewBag.CurrUserName = currentUser.UserName;
            ViewBag.CurrUserPic = currentUser.UserProfilePicture;

            ViewBag.SecUserName = secondUser.UserName;
            ViewBag.SecUserPic = secondUser.UserProfilePicture;

            int exists = 0;
            //check if match exists
            var matchExists = _context.MatchedUsers.Where(mu =>
                mu.UserId == _currentUser.UserId).ToList();//.Where(mu => mu.UserId == secondUser.UserId);

            foreach (var item in matchExists)
            {
                var secondMatch = _context.MatchedUsers.Where(s => s.MatchId == item.MatchId)
                    .Where(s => s.UserId == secondUser.UserId).ToList();
                if (secondMatch.Count() != 0)
                {
                    var oldMatch = _context.Matches
                        .Include(usermatch => usermatch.MatchedUsers)
                        .ThenInclude(user => user.User)
                        .Include(artistmatch => artistmatch.MatchedArtists)
                        .ThenInclude(artist => artist.Artist)
                        .Include(trackmatch => trackmatch.MatchedTracks)
                        .ThenInclude(track => track.Track)
                        .SingleOrDefault(m => m.MatchId == secondMatch[0].MatchId);

                    _match.MatchId = oldMatch.MatchId;
                    _match.MatchRate = oldMatch.MatchRate;
                    _match.MatchDate = oldMatch.MatchDate;
                    _match.MatchedUsers = oldMatch.MatchedUsers;
                    _match.MatchedArtists = oldMatch.MatchedArtists;
                    _match.MatchedTracks = oldMatch.MatchedTracks;

                    exists = 1;
                    return View(_match);
                }
            }
//            var matchExists = await _context.MatchedUsers.FirstOrDefaultAsync((d => d.UserId == _currentUser.UserId && d.UserId == _secondUser.UserId) );

           


            

            if (exists == 0)
            {
                DateTime today = DateTime.Today;
                _match.MatchDate = today;
                _match.MatchName = currentUser.UserName + " and " + secondUser.UserName;
                await _context.Matches.AddAsync(_match);
                await _context.SaveChangesAsync();
            }
            
            

            await AddUsersMatches(currentUser, _match);
            await AddUsersMatches(secondUser, _match);

            await AddMatchingTracks(currentUser, secondUser, _match);
            await AddMatchingArtists(currentUser, secondUser, _match);

            await CalculateMatchRate(_match);
            



            return View(_match);
        }
        
        public IActionResult ShowPreviousMatch(string Id)
        {
            var matchId = Int32.Parse(Id);

            //var match = await _context.Matches.FirstOrDefaultAsync(m => m.MatchId == matchId);

            var match = _context.Matches
                .Include(usermatch => usermatch.MatchedUsers)
                .ThenInclude(user => user.User)
                .Include(artistmatch => artistmatch.MatchedArtists)
                .ThenInclude(artist => artist.Artist)
                .Include(trackmatch => trackmatch.MatchedTracks)
                .ThenInclude(track => track.Track)
                .SingleOrDefault(m => m.MatchId == matchId);

            if (match == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var matchedUsers = match.MatchedUsers.OrderBy(u => u.MatchId).ToList();

            if (matchedUsers.Count() == 0)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewBag.CurrUserName = matchedUsers[0].User.UserName;
            ViewBag.CurrUserPic = matchedUsers[0].User.UserProfilePicture;

            ViewBag.SecUserName = matchedUsers[1].User.UserName;
            ViewBag.SecUserPic = matchedUsers[1].User.UserProfilePicture;

            return View("Match", match);
        }

        public async Task CalculateMatchRate(Match match)
        {
            var matchedTrackCount = match.MatchedTracks.Count();
            var matchedArtistCount = match.MatchedArtists.Count();

            match.MatchRate = matchedTrackCount + matchedArtistCount;

            _context.Update(match);
            await _context.SaveChangesAsync();
        }
        
        public async Task AddMatchingTracks(User currentUser, User secondUser, Match match)
        {
            var currentUserTracks = _context.UsersTracks.Where(u => u.UserId == currentUser.UserId).OrderBy(a=> a.TrackId).ToList();

            var secondUserTracks = _context.UsersTracks.Where(s => s.UserId == secondUser.UserId).OrderBy(b => b.TrackId).ToList();

            int current = 0;
            int second = 0;

            while (current < currentUserTracks.Count() && second < secondUserTracks.Count())
            {
                if (String.Equals(currentUserTracks[current].TrackId, secondUserTracks[second].TrackId))
                {
                    //now we got a matching track 
                    //get the Track object from db
                    var matchedTrack = await _context.Tracks.FirstOrDefaultAsync(t => t.TrackId == currentUserTracks[current].TrackId);

                    //create the trackMatch and add objects to it
                    TrackMatch trackMatch = new TrackMatch();

                    trackMatch.Match = match;
                    trackMatch.Track = matchedTrack;

                    match.MatchedTracks.Add(trackMatch);
                    matchedTrack.MatchedTracks.Add(trackMatch);

                    //updating
                    _context.Matches.Update(match);
                    _context.Tracks.Update(matchedTrack);
                    await _context.SaveChangesAsync();

                    current += 1;
                    second += 1;
                }
                if (String.Compare(currentUserTracks[current].TrackId, secondUserTracks[second].TrackId) == -1)
                {
                    current += 1;
                }
                else
                {
                    second += 1;
                }
            }
        }

       
        public async Task AddMatchingArtists(User currentUser, User secondUser, Match match)
        {
            var currentUserArtists = _context.UsersArtists.Where(u => u.UserId == currentUser.UserId).OrderBy(a => a.ArtistId).ToList();

            var secondUserArtists = _context.UsersArtists.Where(s => s.UserId == secondUser.UserId).OrderBy(b => b.ArtistId).ToList();


            int current = 0;
            int second = 0;
            while (current < currentUserArtists.Count() && second < secondUserArtists.Count())
            {
                if (currentUserArtists[current].ArtistId == secondUserArtists[second].ArtistId)
                {
                    //now we got a matching artist 
                    //get the Track object from db
                    var matchedArtist = await _context.Artists.FirstOrDefaultAsync(a => a.ArtistId == currentUserArtists[current].ArtistId);

                    //create the trackMatch and add objects to it
                    ArtistMatch artistMatch = new ArtistMatch
                    {
                        Match = match,
                        Artist = matchedArtist
                    };

                    match.MatchedArtists.Add(artistMatch);
                    matchedArtist.MatchedArtists.Add(artistMatch);

                    //updating
                    _context.Matches.Update(match);
                    _context.Artists.Update(matchedArtist);
                    await _context.SaveChangesAsync();
                    current += 1;
                    second += 1;
                }

Views/Users/Delete.cshtml
@model MatchMusic.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserCode)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Home" asp-route-id=@Model.UserId>Back to Home</a>
    </form>
</div>

Views/Users/Home.cshtml
@model MatchMusic.Models.User

@{
    ViewData["Title"] = "Details";
}

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
<style>
    input[type=text] {
        width: 80%;
        padding: 15px 22px;
        margin: 10px 5px;
        box-sizing: border-box;
        font-size: 25px;
        background: lightgrey;
    }

    btn btn-success {
        border: 10px solid #073642;
    }

</style>
<h2>Welcome @Html.DisplayFor(model => model.UserName)</h2>
<div class="jumbotron">
<div class="row">
        <div class="col-md-4">
            <img width="250" height="250" src="@Html.DisplayFor(model => model.UserProfilePicture)">
        </div>
        <div class="col-md-8">
            <h2> Share your code with friends and start matching!</h2>
            <input type="text" name="code" value="@Html.DisplayFor(model => model.UserCode)" readonly>
        </div>
    </div>

    <hr />
    <div class="row">
        <h2><strong>Enter a Code</strong></h2>
        
        @if (ViewBag.MyString != null)
        {
            <div class ="col-md-3">
                <p> Code you entered was invalid. Please try again.</p>
            </div>
        }
        <hr />

       
        <div class="input-group md-form form-sm form-2 pl-0">
            <form method="post" action="@Url.Action("Match", "Matches")">
                <input class="form-control my-0 py-1" placeholder="Enter a Code" aria-label="Enter a Code" name="userCode">
            </form>
            <div class="input-group-append">
                <span class="input-group-text" id="basic-text1">
                    <i class="fas fa-search" aria-hidden="true"></i>
                </span>
            </div>
        </div>

    </div>

    <hr/>
    <h2><strong>Matches</strong></h2>
    <hr/>
    @if (Model.MatchedUsers.ToList().Count() != 0)
    {
        var matches = Model.MatchedUsers.OrderBy(a => a.MatchId).ToList();
        for (int i = 0; i < matches.Count(); i++)
        {
            <form method="post" action ="@Url.Action("ShowPreviousMatch", "Matches", new {Id = @matches[i].Match.MatchId.ToString()})">
                <div class="row">
                    <button class="btn btn-success" type ="submit" name ="matchId"><i class="fa fa-angle-right" aria-hidden="true" ></i>
                        @matches[i].Match.MatchName in @matches[i].Match.MatchDate.Date.ToString("dd / MM / yyyy") match rate is %@matches[i].Match.MatchRate </button>
                    <br/>
                    <br/>
                    <br/>
                </div>
            </form>
            <div class="row">
                <br/>
            </div>
            
        }
        
    }
    
    <hr/>
    <div class="row">
        <form method="get" action="@Url.Action("Delete", "Users", new {id = Model.UserId})">
            <button class="btn btn-danger" type="submit">Delete Account</button> 
        </form>
    </div>

</div>

    
    